version: "2"
services:

  uwsgi:
    build: ./web-app
    volumes:
      - ./web-app:/var/www/
    ports:
      - "3031:3031"
    # Local development env 
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=tagdb"
      - "DB_USER=root"
      - "DB_PASSWORD=root"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - mysql

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"

  # Local development settings
  mysql:
    build: ./mysql
    command: mysqld --character-set-server=utf8 --character-set-client=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./mysql/volumes:/var/lib/mysql
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.conf
    environment:
      - "MYSQL_DATABASE=tagdb"
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
        - "3306:3306"
